-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Aisf.Object.Champion exposing (email, firstName, id, lastName, proExperiences, sport)

import Aisf.InputObject
import Aisf.Interface
import Aisf.Object
import Aisf.Scalar
import Aisf.ScalarCodecs
import Aisf.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


email : SelectionSet String Aisf.Object.Champion
email =
    Object.selectionForField "String" "email" [] Decode.string


firstName : SelectionSet String Aisf.Object.Champion
firstName =
    Object.selectionForField "String" "firstName" [] Decode.string


id : SelectionSet Aisf.ScalarCodecs.Id Aisf.Object.Champion
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Aisf.ScalarCodecs.codecs |> Aisf.Scalar.unwrapCodecs |> .codecId |> .decoder)


lastName : SelectionSet String Aisf.Object.Champion
lastName =
    Object.selectionForField "String" "lastName" [] Decode.string


proExperiences : SelectionSet decodesTo Aisf.Object.ProExperience -> SelectionSet (List decodesTo) Aisf.Object.Champion
proExperiences object_ =
    Object.selectionForCompositeField "proExperiences" [] object_ (identity >> Decode.list)


sport : SelectionSet decodesTo Aisf.Object.Sport -> SelectionSet decodesTo Aisf.Object.Champion
sport object_ =
    Object.selectionForCompositeField "sport" [] object_ identity
