-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Aisf.Object.Medal exposing (competition, id, medalType, specialty, year)

import Aisf.InputObject
import Aisf.Interface
import Aisf.Object
import Aisf.Scalar
import Aisf.ScalarCodecs
import Aisf.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


competition : SelectionSet String Aisf.Object.Medal
competition =
    Object.selectionForField "String" "competition" [] Decode.string


id : SelectionSet Aisf.ScalarCodecs.Id Aisf.Object.Medal
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Aisf.ScalarCodecs.codecs |> Aisf.Scalar.unwrapCodecs |> .codecId |> .decoder)


medalType : SelectionSet Int Aisf.Object.Medal
medalType =
    Object.selectionForField "Int" "medalType" [] Decode.int


specialty : SelectionSet String Aisf.Object.Medal
specialty =
    Object.selectionForField "String" "specialty" [] Decode.string


year : SelectionSet Int Aisf.Object.Medal
year =
    Object.selectionForField "Int" "year" [] Decode.int
