-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Aisf.Object.ProExperience exposing (companyName, contact, description, id, sectors, title, website)

import Aisf.InputObject
import Aisf.Interface
import Aisf.Object
import Aisf.Scalar
import Aisf.ScalarCodecs
import Aisf.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


companyName : SelectionSet (Maybe String) Aisf.Object.ProExperience
companyName =
    Object.selectionForField "(Maybe String)" "companyName" [] (Decode.string |> Decode.nullable)


contact : SelectionSet (Maybe String) Aisf.Object.ProExperience
contact =
    Object.selectionForField "(Maybe String)" "contact" [] (Decode.string |> Decode.nullable)


description : SelectionSet (Maybe String) Aisf.Object.ProExperience
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


id : SelectionSet Aisf.ScalarCodecs.Id Aisf.Object.ProExperience
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Aisf.ScalarCodecs.codecs |> Aisf.Scalar.unwrapCodecs |> .codecId |> .decoder)


sectors : SelectionSet decodesTo Aisf.Object.Sector -> SelectionSet (List decodesTo) Aisf.Object.ProExperience
sectors object_ =
    Object.selectionForCompositeField "sectors" [] object_ (identity >> Decode.list)


title : SelectionSet (Maybe String) Aisf.Object.ProExperience
title =
    Object.selectionForField "(Maybe String)" "title" [] (Decode.string |> Decode.nullable)


website : SelectionSet (Maybe String) Aisf.Object.ProExperience
website =
    Object.selectionForField "(Maybe String)" "website" [] (Decode.string |> Decode.nullable)
