-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Aisf.Object.Winner exposing (firstName, lastName, position)

import Aisf.InputObject
import Aisf.Interface
import Aisf.Object
import Aisf.Scalar
import Aisf.ScalarCodecs
import Aisf.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


firstName : SelectionSet String Aisf.Object.Winner
firstName =
    Object.selectionForField "String" "firstName" [] Decode.string


lastName : SelectionSet String Aisf.Object.Winner
lastName =
    Object.selectionForField "String" "lastName" [] Decode.string


position : SelectionSet Int Aisf.Object.Winner
position =
    Object.selectionForField "Int" "position" [] Decode.int
