-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Aisf.InputObject exposing (FileParams, FileParamsOptionalFields, FileParamsRequiredFields, MedalParams, MedalParamsRequiredFields, ProExperienceParams, ProExperienceParamsRequiredFields, SectorParams, SectorParamsRequiredFields, buildFileParams, buildMedalParams, buildProExperienceParams, buildSectorParams, encodeFileParams, encodeMedalParams, encodeProExperienceParams, encodeSectorParams)

import Aisf.Interface
import Aisf.Object
import Aisf.Scalar
import Aisf.ScalarCodecs
import Aisf.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


buildFileParams : FileParamsRequiredFields -> (FileParamsOptionalFields -> FileParamsOptionalFields) -> FileParams
buildFileParams required fillOptionals =
    let
        optionals =
            fillOptionals
                { base64 = Absent }
    in
    { base64 = optionals.base64, filename = required.filename }


type alias FileParamsRequiredFields =
    { filename : String }


type alias FileParamsOptionalFields =
    { base64 : OptionalArgument String }


{-| Type for the FileParams input object.
-}
type alias FileParams =
    { base64 : OptionalArgument String
    , filename : String
    }


{-| Encode a FileParams into a value that can be used as an argument.
-}
encodeFileParams : FileParams -> Value
encodeFileParams input =
    Encode.maybeObject
        [ ( "base64", Encode.string |> Encode.optional input.base64 ), ( "filename", Encode.string input.filename |> Just ) ]


buildMedalParams : MedalParamsRequiredFields -> MedalParams
buildMedalParams required =
    { competition = required.competition, id = required.id, medalType = required.medalType, specialty = required.specialty, year = required.year }


type alias MedalParamsRequiredFields =
    { competition : String
    , id : String
    , medalType : Int
    , specialty : String
    , year : Int
    }


{-| Type for the MedalParams input object.
-}
type alias MedalParams =
    { competition : String
    , id : String
    , medalType : Int
    , specialty : String
    , year : Int
    }


{-| Encode a MedalParams into a value that can be used as an argument.
-}
encodeMedalParams : MedalParams -> Value
encodeMedalParams input =
    Encode.maybeObject
        [ ( "competition", Encode.string input.competition |> Just ), ( "id", Encode.string input.id |> Just ), ( "medalType", Encode.int input.medalType |> Just ), ( "specialty", Encode.string input.specialty |> Just ), ( "year", Encode.int input.year |> Just ) ]


buildProExperienceParams : ProExperienceParamsRequiredFields -> ProExperienceParams
buildProExperienceParams required =
    { companyName = required.companyName, contact = required.contact, description = required.description, id = required.id, sector = required.sector, title = required.title, website = required.website }


type alias ProExperienceParamsRequiredFields =
    { companyName : String
    , contact : String
    , description : String
    , id : String
    , sector : SectorParams
    , title : String
    , website : String
    }


{-| Type for the ProExperienceParams input object.
-}
type alias ProExperienceParams =
    { companyName : String
    , contact : String
    , description : String
    , id : String
    , sector : SectorParams
    , title : String
    , website : String
    }


{-| Encode a ProExperienceParams into a value that can be used as an argument.
-}
encodeProExperienceParams : ProExperienceParams -> Value
encodeProExperienceParams input =
    Encode.maybeObject
        [ ( "companyName", Encode.string input.companyName |> Just ), ( "contact", Encode.string input.contact |> Just ), ( "description", Encode.string input.description |> Just ), ( "id", Encode.string input.id |> Just ), ( "sector", encodeSectorParams input.sector |> Just ), ( "title", Encode.string input.title |> Just ), ( "website", Encode.string input.website |> Just ) ]


buildSectorParams : SectorParamsRequiredFields -> SectorParams
buildSectorParams required =
    { id = required.id, name = required.name }


type alias SectorParamsRequiredFields =
    { id : String
    , name : String
    }


{-| Type for the SectorParams input object.
-}
type alias SectorParams =
    { id : String
    , name : String
    }


{-| Encode a SectorParams into a value that can be used as an argument.
-}
encodeSectorParams : SectorParams -> Value
encodeSectorParams input =
    Encode.maybeObject
        [ ( "id", Encode.string input.id |> Just ), ( "name", Encode.string input.name |> Just ) ]
