-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Aisf.Mutation exposing (CreateChampionRequiredArguments, createChampion)

import Aisf.InputObject
import Aisf.Interface
import Aisf.Object
import Aisf.Scalar
import Aisf.ScalarCodecs
import Aisf.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


type alias CreateChampionRequiredArguments =
    { email : String
    , firstName : String
    , lastName : String
    , proExperiences : List Aisf.InputObject.ProExperienceParams
    , sport : String
    }


createChampion : CreateChampionRequiredArguments -> SelectionSet decodesTo Aisf.Object.Champion -> SelectionSet (Maybe decodesTo) RootMutation
createChampion requiredArgs object_ =
    Object.selectionForCompositeField "createChampion" [ Argument.required "email" requiredArgs.email Encode.string, Argument.required "firstName" requiredArgs.firstName Encode.string, Argument.required "lastName" requiredArgs.lastName Encode.string, Argument.required "proExperiences" requiredArgs.proExperiences (Aisf.InputObject.encodeProExperienceParams |> Encode.list), Argument.required "sport" requiredArgs.sport Encode.string ] object_ (identity >> Decode.nullable)
