-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Aisf.Mutation exposing (CreateChampionRequiredArguments, UpdateChampionOptionalArguments, UpdateChampionRequiredArguments, createChampion, updateChampion)

import Aisf.InputObject
import Aisf.Interface
import Aisf.Object
import Aisf.Scalar
import Aisf.ScalarCodecs
import Aisf.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


type alias CreateChampionRequiredArguments =
    { email : String
    , firstName : String
    , intro : String
    , isMember : Bool
    , lastName : String
    , medals : List Aisf.InputObject.MedalParams
    , proExperiences : List Aisf.InputObject.ProExperienceParams
    , sport : String
    , yearsInFrenchTeam : List Int
    }


createChampion : CreateChampionRequiredArguments -> SelectionSet decodesTo Aisf.Object.Champion -> SelectionSet (Maybe decodesTo) RootMutation
createChampion requiredArgs object_ =
    Object.selectionForCompositeField "createChampion" [ Argument.required "email" requiredArgs.email Encode.string, Argument.required "firstName" requiredArgs.firstName Encode.string, Argument.required "intro" requiredArgs.intro Encode.string, Argument.required "isMember" requiredArgs.isMember Encode.bool, Argument.required "lastName" requiredArgs.lastName Encode.string, Argument.required "medals" requiredArgs.medals (Aisf.InputObject.encodeMedalParams |> Encode.list), Argument.required "proExperiences" requiredArgs.proExperiences (Aisf.InputObject.encodeProExperienceParams |> Encode.list), Argument.required "sport" requiredArgs.sport Encode.string, Argument.required "yearsInFrenchTeam" requiredArgs.yearsInFrenchTeam (Encode.int |> Encode.list) ] object_ (identity >> Decode.nullable)


type alias UpdateChampionOptionalArguments =
    { profilePicture : OptionalArgument Aisf.InputObject.FileParams }


type alias UpdateChampionRequiredArguments =
    { email : String
    , firstName : String
    , id : String
    , intro : String
    , isMember : Bool
    , lastName : String
    , medals : List Aisf.InputObject.MedalParams
    , proExperiences : List Aisf.InputObject.ProExperienceParams
    , sport : String
    , yearsInFrenchTeam : List Int
    }


updateChampion : (UpdateChampionOptionalArguments -> UpdateChampionOptionalArguments) -> UpdateChampionRequiredArguments -> SelectionSet decodesTo Aisf.Object.Champion -> SelectionSet (Maybe decodesTo) RootMutation
updateChampion fillInOptionals requiredArgs object_ =
    let
        filledInOptionals =
            fillInOptionals { profilePicture = Absent }

        optionalArgs =
            [ Argument.optional "profilePicture" filledInOptionals.profilePicture Aisf.InputObject.encodeFileParams ]
                |> List.filterMap identity
    in
    Object.selectionForCompositeField "updateChampion" (optionalArgs ++ [ Argument.required "email" requiredArgs.email Encode.string, Argument.required "firstName" requiredArgs.firstName Encode.string, Argument.required "id" requiredArgs.id Encode.string, Argument.required "intro" requiredArgs.intro Encode.string, Argument.required "isMember" requiredArgs.isMember Encode.bool, Argument.required "lastName" requiredArgs.lastName Encode.string, Argument.required "medals" requiredArgs.medals (Aisf.InputObject.encodeMedalParams |> Encode.list), Argument.required "proExperiences" requiredArgs.proExperiences (Aisf.InputObject.encodeProExperienceParams |> Encode.list), Argument.required "sport" requiredArgs.sport Encode.string, Argument.required "yearsInFrenchTeam" requiredArgs.yearsInFrenchTeam (Encode.int |> Encode.list) ]) object_ (identity >> Decode.nullable)
