-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Aisf.Object exposing (Champion(..), Medal(..), ProExperience(..))


type Champion
    = Champion


type Medal
    = Medal


type ProExperience
    = ProExperience
