-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Aisf.Object exposing (Champion(..), Event(..), Medal(..), Picture(..), ProExperience(..), Sector(..))


type Champion
    = Champion


type Event
    = Event


type Medal
    = Medal


type Picture
    = Picture


type ProExperience
    = ProExperience


type Sector
    = Sector
