-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Aisf.Query exposing (ChampionRequiredArguments, ChampionsWithMedalInSportRequiredArguments, allChampions, champion, championsWithMedalInSport, getMembers)

import Aisf.InputObject
import Aisf.Interface
import Aisf.Object
import Aisf.Scalar
import Aisf.ScalarCodecs
import Aisf.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


allChampions : SelectionSet decodesTo Aisf.Object.Champion -> SelectionSet (List decodesTo) RootQuery
allChampions object_ =
    Object.selectionForCompositeField "allChampions" [] object_ (identity >> Decode.list)


type alias ChampionRequiredArguments =
    { id : Aisf.ScalarCodecs.Id }


champion : ChampionRequiredArguments -> SelectionSet decodesTo Aisf.Object.Champion -> SelectionSet decodesTo RootQuery
champion requiredArgs object_ =
    Object.selectionForCompositeField "champion" [ Argument.required "id" requiredArgs.id (Aisf.ScalarCodecs.codecs |> Aisf.Scalar.unwrapEncoder .codecId) ] object_ identity


type alias ChampionsWithMedalInSportRequiredArguments =
    { sport : String }


championsWithMedalInSport : ChampionsWithMedalInSportRequiredArguments -> SelectionSet decodesTo Aisf.Object.Champion -> SelectionSet (List decodesTo) RootQuery
championsWithMedalInSport requiredArgs object_ =
    Object.selectionForCompositeField "championsWithMedalInSport" [ Argument.required "sport" requiredArgs.sport Encode.string ] object_ (identity >> Decode.list)


getMembers : SelectionSet decodesTo Aisf.Object.Champion -> SelectionSet (List decodesTo) RootQuery
getMembers object_ =
    Object.selectionForCompositeField "getMembers" [] object_ (identity >> Decode.list)
