-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Aisf.ScalarCodecs exposing (Id, codecs)

import Aisf.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias Id =
    Aisf.Scalar.Id


codecs : Aisf.Scalar.Codecs Id
codecs =
    Aisf.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        }
